### PR TITLE
Fix types

### LINKED ISSUE #20: Keystore types
It appears that the Keystore types are out-of-date with the implementation found at orbit-db-keystore. There is no longer a default-level create but rather a constructor and an "open" function.

### PR DESCRIPTION
**Pull request by rigwild**
Fixes #20

 - Add `orbit-db-cache` typings
 - Multiple fixes (missing return type/parameter)
 - Added missing `_addOperation` options (see #22)
 - Fix #20

### CODE REVIEW

**Comment by rigwild** [comment]
Hey @aphelionz , I see that you are replicating this in new commits. You should probably look into it. Putting `any` types everywhere is not a good solution.

**Comment by aphelionz** [comment]
Yeah I know, I had to get it working under a really tight time crunch. Thanks for fixing!

**Review by aphelionz — APPROVED** [review]

**Comment by aphelionz** [comment]
Approved, can merge after the conflicts are fixed

**Comment by rigwild** [comment]
I'm not sure for `Keystore.d.ts`.

**Comment by aphelionz** [comment]
I'm not sure either. Create should definitely return a promise of a keystore and verify should definitely return a promise of a boolean.

Also I need to learn more about how these Typescript bindings work. Is there any way to write tests for these?

**Comment by rigwild** [comment]
I can't find the `create` method. Are you sure it has not been removed ?
See https://github.com/orbitdb/orbit-db-keystore/blob/master/src/keystore.js


> Also I need to learn more about how these Typescript bindings work. Is there any way to write tests for these?

What you could do is to write a simple TypeScript program that makes use of tested types and check if it compiles successfully without errors/warnings.

**Comment by aphelionz** [comment]
Yes, sorry, `create` was deleted. I also opened #25

**Comment by aphelionz** [comment]
I'm satisfied with these changes for now :+1:

**Comment by rigwild** [comment]
@aphelionz Don't forget #23 😉

**Pull request merged**
